# Generated by Django 5.1.4 on 2024-12-19 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +234XXXXXXXXXX', regex='^\\+?234\\d{10}$')]),
        ),
    ]
