# Generated by Django 5.1.4 on 2025-03-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_subscriptionplan_property_boost_expiry_and_more'),
        ('properties', '0006_auto_20250311_0048'),
    ]

    operations = [
    ]
